### PR TITLE
fix: implement multi-date event display

### PR DESCRIPTION
**Pull request by zach-aries**
Checks to see if the start date & end date have a difference > 24hrs. 
If so it will display start and end date, otherwise just start date.

---

**Acceptance Testing**

1. Create a multi-date, single date & reoccuring event.
2. Test the following shortcodes to make sure that the event date is displayed properly:
- [showpass_events type="list" detail_page='event-detail' template='grid']
- [showpass_events type="list" detail_page='event-detail' template='list']
- [showpass_events type="detail"]
- [showpass_pricing_table]

### CODE REVIEW

**Comment by marc-thomas** [comment]
Hey @zach-aries.

For the multi date, I think it would make more sense if it read

calendar-icon: Stats: Date @ Time MST
calendar-icon: Ends: Date @ Time MST

Please see how we do it on the event detail page. https://www.showpass.com/kingsprimetv/

**Comment by zach-aries** [comment]
> Hey @zach-aries.
> 
> For the multi date, I think it would make more sense if it read
> 
> calendar-icon: Stats: Date @ Time MST
> calendar-icon: Ends: Date @ Time MST
> 
> Please see how we do it on the event detail page. https://www.showpass.com/kingsprimetv/

Okay, I can update. 
I was just copying the way it was done in `recurring event` to match the rest of the plugin. Would you like me to update that as well?

**Comment by marc-thomas** [comment]
> > Hey @zach-aries.
> > For the multi date, I think it would make more sense if it read
> > calendar-icon: Stats: Date @ Time MST
> > calendar-icon: Ends: Date @ Time MST
> > Please see how we do it on the event detail page. https://www.showpass.com/kingsprimetv/
> 
> Okay, I can update.
> I was just copying the way it was done in `recurring event` to match the rest of the plugin.
> Would you like me to update that as well?

Hey, I think we can improve on this further for recurring events as well. We might want to consider adding the "Multiple Dates" or "Multiple Times" labels similar to the public site. Let me know your thoughts.

**Comment by zach-aries** [comment]
> > > Hey @zach-aries.
> > > For the multi date, I think it would make more sense if it read
> > > calendar-icon: Stats: Date @ Time MST
> > > calendar-icon: Ends: Date @ Time MST
> > > Please see how we do it on the event detail page. https://www.showpass.com/kingsprimetv/
> > 
> > 
> > Okay, I can update.
> > I was just copying the way it was done in `recurring event` to match the rest of the plugin.
> > Would you like me to update that as well?
> 
> Hey, I think we can improve on this further for recurring events as well. We might want to consider adding the "Multiple Dates" or "Multiple Times" labels similar to the public site. Let me know your thoughts.

Agreed, I'll add a similar feature as discussed.

**Pull request merged**
